// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcJ_2GJRyoKXIGQKrZZAuUwovIZp1HeTc',
    appId: '1:110451384524:web:81b5da578e87de0d50a269',
    messagingSenderId: '110451384524',
    projectId: 'telehealth-991c9',
    authDomain: 'telehealth-991c9.firebaseapp.com',
    databaseURL: 'https://telehealth-991c9-default-rtdb.firebaseio.com',
    storageBucket: 'telehealth-991c9.appspot.com',
    measurementId: 'G-24SWXFN3XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBza0fV3oUnvfWjNzkmAaYrN7fZt87BLfo',
    appId: '1:110451384524:android:9f6ec297f286fada50a269',
    messagingSenderId: '110451384524',
    projectId: 'telehealth-991c9',
    databaseURL: 'https://telehealth-991c9-default-rtdb.firebaseio.com',
    storageBucket: 'telehealth-991c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVgZXvr1bJNkJG2NxJdOHczuFojFgwrMQ',
    appId: '1:110451384524:ios:bcebc5cd8d12158d50a269',
    messagingSenderId: '110451384524',
    projectId: 'telehealth-991c9',
    databaseURL: 'https://telehealth-991c9-default-rtdb.firebaseio.com',
    storageBucket: 'telehealth-991c9.appspot.com',
    iosBundleId: 'com.example.telehealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVgZXvr1bJNkJG2NxJdOHczuFojFgwrMQ',
    appId: '1:110451384524:ios:bcebc5cd8d12158d50a269',
    messagingSenderId: '110451384524',
    projectId: 'telehealth-991c9',
    databaseURL: 'https://telehealth-991c9-default-rtdb.firebaseio.com',
    storageBucket: 'telehealth-991c9.appspot.com',
    iosBundleId: 'com.example.telehealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcJ_2GJRyoKXIGQKrZZAuUwovIZp1HeTc',
    appId: '1:110451384524:web:fa5961d05b51fad550a269',
    messagingSenderId: '110451384524',
    projectId: 'telehealth-991c9',
    authDomain: 'telehealth-991c9.firebaseapp.com',
    databaseURL: 'https://telehealth-991c9-default-rtdb.firebaseio.com',
    storageBucket: 'telehealth-991c9.appspot.com',
    measurementId: 'G-WPBEDR1GN2',
  );

}